displayName=Alch Ledger
author=iotaaa
description=Shows which items profit from High Level Alchemy, outlines them by profit tier and logs your alching profit
tags=alch,alchemy,high alch,magic,profit,money,ironman,nature rune
plugins=com.alchledger.AlchLedgerPlugin
version=
build=standard
